# Generated by Django 6.0.2 on 2026-02-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
